# siteconfig.yml

# Each entry under the top level 'Sites' creates a new set of AWS resources under that name. 
Sites: 

  site1:
    name: West Mountain Drive
    alias: WMD
    country: USA
    tz: -8
    lat: 334.34293028
    lng: -119.68112801
    elevation: 317.75

